### PR TITLE
Fix supportRef function for preact

### PR DESCRIPTION
**Pull request by SpaNb4**
Fixes the issue described in https://github.com/ant-design/ant-design/pull/44135

Why the issue exists:
The highlighted code in `rc-dropdown` returns `true` for react and `false` for preact
https://github.com/react-component/dropdown/blob/master/src/Overlay.tsx#L25
<details>
  <summary>Screenshot</summary>

image
</details>

That's why the focus doesn't shift to the menu when using preact.

Now let's take a look at the `supportRef` code and add some console.log to it for debugging:
<details>
  <summary>Screenshot</summary>

image
</details>

And here are the results:
<details>
  <summary>react</summary>

image
</details>

<details>
  <summary>preact</summary>

image
</details>

So, based on the screenshots above, we can conclude that in the case of preact, the `nodeOrComponent`  is a `function`, not an `object`, so the second condition is fulfilled and `false` is returned.

And to fix this I added an additional condition because in the screenshot above you can see that preact as well as react have a `$$typeof` property equal to `Symbol(react.forward_ref)`
image

### CODE REVIEW

**Comment by SpaNb4** [comment]
@MadCcc @zombieJ Could you please review this PR?

**Comment by mellis481** [comment]
@MadCcc @afc163 @zombieJ Can you please review and merge this PR? It's critical for my team.

**Comment by afc163** [comment]
@MadCcc 看看这个

**Comment by SpaNb4** [comment]
@MadCcc Could you please review this PR?

**Comment by mellis481** [comment]
@MadCcc Bump.

**Comment by mellis481** [comment]
@MadCcc Help!

**Comment by mellis481** [comment]
@afc163 Can you please help get this PR merged?

**Comment by afc163** [comment]
ping @MadCcc @zombieJ

**Comment by MadCcc** [comment]
Could add test for preact?

**Comment by zombieJ** [comment]
Checked for React 16, seems safe to merge.

**Review by zombieJ — APPROVED** [review]

**Pull request merged**
